:schedule:
  p_parser_job:
    cron: '*/5 * * * *'
    args: ['p']
    class: ParserJob
  m_parser_job:
    cron: '*/1 * * * *'
    args: ['m']
    class: ParserJob
  kondratio_parser_job:
    cron: '*/10 * * * *'
    class: KondratioParserJob
